/**
 * The paragraph the model read for this decision, line by line.
 *
 * Every line is a `<span>` rather than one blob of text so the lines a question is answered from
 * can be lit when that question is hovered — `move_x` lights the `x:` offset line, `rim` lights
 * the whole lettered block, `yaw` lights the wrist error. Hovering a *line* works the other way
 * and tells the panel which questions read it, so the link can be followed from either end.
 *
 * Nothing here is generated by the page: the text is exactly the string the server sent to the
 * model, kept verbatim in the bundle, and this component only decides which of its lines to
 * brighten.
 */
import { parseStateText } from "../data/stateText";
import type { StateLine } from "../data/stateText";

export function StateText({ state, hot, onHot }: {
  state: string;
  hot: string | null;
  onHot: (qid: string | null) => void;
}) {
  const lines: StateLine[] = parseStateText(state);
  return (
    <pre className="statetext" data-testid="state-text">
      {lines.map((line) => {
        const lit = hot !== null && line.qids.includes(hot);
        return (
          <span
            key={line.index}
            className={`statetext__line${lit ? " statetext__line--hot" : ""}`}
            data-testid={`state-line-${line.index}`}
            data-kind={line.kind}
            data-qids={line.qids.join(" ")}
            data-hot={lit ? "true" : undefined}
            onMouseEnter={() => line.qids.length > 0 && onHot(line.qids[0])}
            onMouseLeave={() => onHot(null)}
          >
            {line.text === "" ? " " : line.text}
            {"\n"}
          </span>
        );
      })}
    </pre>
  );
}
